trigger:
    - none

pool:
  vmImage: 'macos-latest'

jobs:
  - job: IOS_BUILD
    timeoutInMinutes: 0 
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '16.x'
        displayName: 'Install Node.js'
      - task: CmdLine@2
        displayName: 'yarn install'
        inputs:
          script: 'yarn install'

      - task: CocoaPods@0
        displayName: 'Install CocoaPods'
        inputs:
          workingDirectory: 'ios'
      
      - script: |
          sudo xcode-select -s /Applications/Xcode_14.2.app
          # sudo xcode-select -s /Applications/Xcode_13.4.app
        displayName: Selects a specific version of Xcode

      - task: Xcode@5
        displayName: 'Build IPA'
        inputs:
          actions: 'archive'
          configuration: 'Release'
          sdk: 'iphoneos'
          xcWorkspacePath: 'ios/Asociar.xcworkspace'
          scheme: 'Asociar'
          packageApp: true
          exportPath: 'output'
          signingOption: 'manual'