# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: CmdLine@2
  displayName: Curl Example
  inputs:
    script: 'curl --location "https://qa.gamma.apsy-dev.net/api/update" --header "Content-Type: application/json" --data "{\"token\":\"$(token)\"}"'
