mutation createDirectMessage($text:String!, $conversationId: Int!, $receiverId: Int!){
 message_createDirectMessage(input: {
   text: $text, conversationId:$conversationId
 }, receiverId: $receiverId) {
   status
   result {
     id
     createdAt
     createdDate
     conversation {
       messages{
         text
       }
     } 
   }
 }
}