export { default as Brush1IconSet } from "./brush-1";
export { default as BrushIconSet } from "./brush";
export { default as ColorSwatchIconSet } from "./color-swatch";
export { default as ColorfilterIconSet } from "./colorfilter";
export { default as ComponentIconSet } from "./component";
export { default as CopyIconSet } from "./copy";
export { default as Ellipse446IconSet } from "./Ellipse 446";
export { default as EraserIconSet } from "./eraser";
export { default as GlassIconSet } from "./glass";
export { default as LayerIconSet } from "./layer";
export { default as Line13IconSet } from "./Line 13";
export { default as MagicpenIconSet } from "./magicpen";
export { default as MainComponentIconSet } from "./main-component";
export { default as PaintbucketIconSet } from "./paintbucket";
export { default as PathIconSet } from "./path";
export { default as PenToolIconSet } from "./pen-tool";
export { default as RulerpenIconSet } from "./ruler&pen";
export { default as RulerIconSet } from "./ruler";
export { default as ScissorIconSet } from "./scissor";
export { default as VectorIconSet } from "./Vector";
